AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  slack-lottery-bot

  Sample SAM Template for slack-lottery-bot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  SelectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: select/
      Handler: select
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /select
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          VERIFICATIONTOKEN: !Ref VERIFICATIONTOKEN # slack verification token
          BOTTOKEN: !Ref BOTTOKEN # slack bot token
          OAUTHTOKEN: !Ref OAUTHTOKEN
  LotteryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lottery/
      Handler: lottery
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /lottery
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          VERIFICATIONTOKEN: !Ref VERIFICATIONTOKEN # slack verification token
          BOTTOKEN: !Ref BOTTOKEN # slack bot token
          OAUTHTOKEN: !Ref OAUTHTOKEN
Parameters:
  VERIFICATIONTOKEN:
    Type: String
  BOTTOKEN:
    Type: String
  OAUTHTOKEN:
    Type: String

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SelectAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SelectFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt SelectFunction.Arn
  SelectFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SelectFunctionRole.Arn
  LotteryAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  LotteryFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt LotteryFunction.Arn
  LotteryFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LotteryFunctionRole.Arn
